config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  # People resource
  resources :people, defaults: { format: :html } do
    # Details nested resource
    resources :details, defaults: { format: :html }
  end

  # Route for JSON format for both people and details resources
  namespace :api, defaults: { format: :json } do
    resources :people, only: [:index, :show, :create, :update, :destroy] do
      resources :details, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :person

  validates :detail_type, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :details, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/details_controller.rb
# frozen_string_literal: true

class DetailsController < ApplicationController
  before_action :set_person
  before_action :set_detail, only: [:edit, :update, :destroy]

  # GET /people/:person_id/details/new
  def new
    @detail = @person.details.build
    render partial: 'details/new'
  end

  # GET /people/:person_id/details/:id/edit
  def edit
    render partial: 'details/edit'
  end

  # GET /people/:person_id/details
  # GET /people/:person_id/details.json
  def index
    @details = @person.details

    respond_to do |format|
      format.html { render partial: 'details/index'}# Render the HTML view
      format.json { render json: @details } # Respond with JSON data
    end
  end

  # POST /people/:person_id/details
  # POST /people/:person_id/details.json
  def create
    @detail = @person.details.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to person_details_path(@person), notice: 'Detail was successfully created.' }
        format.json { render json: @detail, status: :created }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/:person_id/details/:id
  # PATCH/PUT /people/:person_id/details/:id.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to person_details_path(@person), notice: 'Detail was successfully updated.' }
        format.json { render json: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/:person_id/details/:id
  # DELETE /people/:person_id/details/:id.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to person_details_path(@person), notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_person
    @person = Person.find(params[:person_id])
  end

  def set_detail
    @detail = @person.details.find(params[:id])
  end

  def detail_params
    params.require(:detail).permit(:detail_type, :detail_value)
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/:id/edit
  def edit
  end

  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # Render the HTML view
      format.json { render json: @people } # Respond with JSON data
    end
  end

  # GET /people/:id
  # GET /people/:id.json
  def show
    @details = @person.details
    respond_to do |format|
      format.html {render partial: 'person_details'}# Render the HTML view
      format.json { render json: @person, include: :details } # Respond with JSON data
    end
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to people_path, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/:id
  # PATCH/PUT /people/:id.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to people_path, notice: 'Person was successfully updated.' }
        format.json { render json: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/:id
  # DELETE /people/:id.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def person_params
    params.require(:person).permit(:name, :email)
  end

  def set_person
    @person = Person.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/details/_edit.html.erb
<turbo-frame id="details">
<h1>Edit Detail for <%= @person.name %></h1>

<%= form_with(model: [@person, @detail], url: person_detail_path(@person, @detail), method: :patch) do |form| %>
  <div>
    <%= form.label :detail_type %>
    <%= form.text_field :detail_type %>
  </div>

  <div>
    <%= form.label :detail_value %>
    <%= form.text_field :detail_value %>
  </div>

  <div>
    <%= form.submit "Update Detail" %>
  </div>
<% end %>
</turbo-frame>

app/views/details/_index.html.erb
<turbo-frame id="details">
<h1>Details</h1>

<ul>
  <li> Name: <%= @person.name %></li>
  <li> Email: <%= @person.email %></li>
  <% @details.each do |detail| %>
    <li>
      <%= detail.detail_type %>: <%= detail.detail_value %>
      <%= link_to "Edit", edit_person_detail_path(@person, detail), class: "btn btn-primary btn-sm", "data-turbo-frame": "details" %>
      <%= link_to "Delete", person_detail_path(@person, detail), data: { turbo_method: :delete }, class: "btn btn-danger btn-sm" %>
    </li>
<% end %>
</ul>

  <%= link_to "New Detail", new_person_detail_path(@person), class: "person-link", "data-turbo-frame": "details" %>
</turbo-frame>

app/views/details/_new.html.erb
<turbo-frame id="details">
<h1>New Detail for <%= @person.name %></h1>

<%= form_with(model: [@person, @detail], url: person_details_path(@person), method: :post) do |form| %>
  <div>
    <%= form.label :detail_type %>
    <%= form.text_field :detail_type %>
  </div>

  <div>
    <%= form.label :detail_value %>
    <%= form.text_field :detail_value %>
  </div>

  <div>
    <%= form.submit "Create Detail" %>
  </div>
<% end %>
</turbo-frame>

app/views/details/edit.html.erb
<%= render :partial => 'details/edit' %>

app/views/details/index.html.erb
<%= render :partial => 'details/index' %>

app/views/details/new.html.erb
<%= render :partial => 'details/new' %>

app/views/details/show.html.erb
<h1><%= @detail.detail_type %></h1>

<p><strong>Value:</strong> <%= @detail.detail_value %></p>

<%= link_to "Edit", edit_person_detail_path(@person, @detail) %> |
<%= link_to "Back", person_details_path(@person) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAssessment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_frame_tag 'turbo' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>

<%= form_with(model: @person, url: person_path(@person), method: :patch) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.submit "Update Person" %>
  </div>
<% end %>

app/views/people/index.html.erb
<div class="row">
  <div class="left-panel col-md-6">
    <!-- Left panel content goes here -->
    <h1>People</h1>
    <ul>
      <% @people.each do |person| %>
        <li>
          <%= link_to person.name, person_details_path(person), class: "person-link", "data-turbo-frame": "details" %>
          (<%= person.email %>)
          <%= link_to "Edit", edit_person_path(person), class: "btn btn-primary btn-sm" %>
          <%= link_to "Delete", person_path(person), data: { turbo_method: :delete }, class: "btn btn-danger btn-sm" %>
        </li>
      <% end %>
    </ul>
    <%= link_to "New Person", new_person_path %>
  </div>

  <div class="right-panel col-md-6">
    <!-- Right panel content (details) will be loaded here dynamically -->
    <%= turbo_frame_tag 'details' do %>
      <!-- Details will be loaded here dynamically -->
    <% end %>
  </div>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= form_with(model: @person, url: people_path, method: :post) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.submit "Create Person" %>
  </div>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>

<p><strong>Email:</strong> <%= @person.email %></p>

<%= link_to "Edit", edit_person_path(@person) %> |
<%= link_to "Back", people_path %>